FROM node:16-alpine

RUN apk update \ 
  && apk add bash \
  && rm -rf /var/cache/apk/*

WORKDIR /app

COPY . /app

RUN yarn install

RUN yarn prisma generate

ENTRYPOINT [ "yarn", "init_loop_test_container" ]