version: '3.9'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: abb0r0h
      MYSQL_DATABASE: abborah_local
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - local
  api:
    image: node:16-alpine
    working_dir: /usr/src/abborah
    command: sh -c "yarn debug"
    environment:
      DB_CONNECTION: mysql://root:abb0r0h@db:3306/abborah_local
    volumes:
      - ./scripts/:/usr/src/abborah/scripts/
      - ./prisma/migrations/:/usr/src/abborah/prisma/migrations/
      - ./prisma/schema.prisma/:/usr/src/abborah/prisma/schema.prisma
      - ./dist/:/usr/src/abborah/dist/
      - ./package.json:/usr/src/abborah/package.json
      - ./yarn.lock:/usr/src/abborah/yarn.lock
    ports:
      - "5050:5050"
      - "9222:9222"
    networks:
      - local
    depends_on:
      - db
volumes:
  data:
networks:
  local: