version: '3.9'
services:
  db_integration:
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: abb0r0h
      MYSQL_DATABASE: abborah_test
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    networks:
      - test
  api:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DB_CONNECTION: mysql://root:abb0r0h@db_integration:3307/abborah_test?schema=public
    volumes:
      - .:/app/
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
    ports:
      - 5555:5555
    depends_on:
      - db_integration
    networks:
      - test

networks:
  test: