name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Configure .env for Prisma
        run: echo DB_CONNECTION="mysql://root:abb0r0h@localhost:3307/abborah_test" > prisma/.env

      - name: Install Dependencies
        run: yarn

      - name: Up Db Integration container
        run: docker-compose up -d db_integration

      - name: Generate and Deploy Prisma 
        run: yarn prisma generate && yarn prisma migrate deploy

      - name: Running test
        run: yarn test:coveralls

      - name: running build
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}